### ISSUE TITLE
Conversion of native to units

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_metrics#27]
Since many events will be emitted in a native time unit, I have briefly discussed with @arkgil a convenience for doing so when specifying a metric, something like:

    last_value(..., unit: {:native, :second})

Will automatically get the native value and convert to second without requiring the user to do it explicitly.

**Comment by bryannaegele** [comment]
This is something I was struggling with on how to do elegantly with the prometheus reporter. My initial approach was to add it as a required config as `:base_unit` for the target unit, but I like this approach better. 

Is this the default value you've shown? How would we avoid the user having to define the unit often when `:bytes` would be common in several metrics? There isn't likely to be much conversion there since all of the memory related functions I can think of return `:bytes` by default, but a user could specify other units.

Another thing I considered was whether or not the most common conversion functions should be provided in this library for consistency and convenience, since time and memory conversion functions will need to be implemented in every reporter. Could this be done similarly to `:tag_values` where the most common cases are covered in a generated function, otherwise the user can provide their own?

**Comment by arkgil** [comment]
@bryannaegele we were thinking that if the conversion tuple is provided, we do two things:

- we override the `:unit` in the returned metric spec to the unit we're converting to
- we override `:measurement` by  wrapping it and converting whatever it returns. To implement this, we need to force the `:measurement` to always be a function (currently it can be also a key)

And yes, I agree that we could handle time and byte conversions.
